onlinegroceryshop/urls.py
from django.contrib import admin
from django.urls import path
from groceryapp.views import *
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home,name="home"), 
    path('index/', index,name="index"),
    path('about/',about, name="about"),
    path('main/', main, name="main"),
    path('admin-login/', adminLogin, name="admin_login"),
    path('adminhome/', adminHome, name="adminhome"),
    path('admindashboard/', admin_dashboard, name="admindashboard"),
    path('add-category/', add_category, name="add_category"),
    path('view-category/', view_category, name="view_category"),
    path('edit-category/<int:pid>/', edit_category, name="edit_category"),
    path('delete-category/<int:pid>/', delete_category, name="delete_category"),
    path('add-product/', add_product, name="add_product"),
    path('view-product/', view_product, name="view_product"),
    path('edit-product/<int:pid>/', edit_product, name="edit_product"),
    path('delete-product/<int:pid>/', delete_product, name="delete_product"),
    path('registration/', registration, name="registration"),
    path('userlogin/', userlogin, name="userlogin"),
    path('profile/', profile, name="profile"),
    path('logout/', logoutuser, name="logout"),
    path('change-password/', change_password, name="change_password"),
    path('user-product/<int:pid>/', user_product, name="user_product"),
    path('product-detail/<int:pid>/', product_detail, name="product_detail"),
    path('add-to-cart/<int:pid>/', addToCart, name="addToCart"),
    path('cart/', cart, name="cart"),
    path('incredecre/<int:pid>/', incredecre, name="incredecre"),
    path('deletecart/<int:pid>/', deletecart, name="deletecart"),
    path('booking/', booking, name="booking"),
    path('my-order/', myOrder, name="myorder"),
    path('user-order-track/<int:pid>/', user_order_track, name="user_order_track"),
    path('change-order-status/<int:pid>/', change_order_status, name="change_order_status"),
    path('user-feedback/', user_feedback, name="user_feedback"),
    path('manage-feedback/', manage_feedback, name="manage_feedback"),
    path('delete-feedback/<int:pid>/', delete_feedback, name="delete_feedback"),
    path('payment/', payment, name="payment"), 
    path('feedback-read/<int:pid>/', read_feedback, name="read_feedback"),
    path('manage-order/', manage_order, name="manage_order"), 
    path('delete-order/<int:pid>/', delete_order, name="delete_order"), 
    path('admin-order-track/<int:pid>/', admin_order_track, name="admin_order_track"),
    path('manage-user/', manage_user, name="manage_user"),
    path('delete-user/<int:pid>/', delete_user, name="delete_user"),
    path('admin-change-password/',admin_change_password, name="admin_change_password"),
    path('contact/', contact, name="contact"),
    path('blog/', blog, name="blog"),
    

 
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

groceryapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=100, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name
    

class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=100, null=True, blank=True)
    image = models.FileField(null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    price = models.CharField(max_length=100, null=True, blank=True)
    discount = models.CharField(max_length=100, null=True, blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name
    


class UserProfile(models.Model):
    user = models.ForeignKey (User, on_delete=models.CASCADE, null=True, blank=True)
    mobile = models.CharField(max_length=100, null=True, blank=True)
    address = models.TextField(null=True, blank=True)
    image = models.FileField(null=True, blank=True)
   
    def __str__(self):
        return self.user.username
    

class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    product = models.TextField(default={'objects': []}, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.username
    

ORDERSTATUS = ((1, "Pending"), (2, "Dispatch"), (3, "On the way"), (4, "Delivered"), (5, "Cancel"), (6, "Return"))
class Booking(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    product = models.TextField(default={'objects': []}, null=True, blank=True)
    total = models.CharField(max_length=100, null=True, blank=True)
    status = models.IntegerField(choices=ORDERSTATUS, default=1)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.username
    

STATUS = ((1, "Read"), (2, "Unread"))
class Feedback(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    message = models.TextField(null=True, blank=True)
    status = models.IntegerField(choices=STATUS, default=2)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.username

groceryapp/views.py
from django.shortcuts import render,redirect,HttpResponse
from django.contrib.auth import authenticate,login, logout
from .models import Category,Product,User,UserProfile,Cart,Booking,ORDERSTATUS,Feedback,STATUS
from django.contrib import messages
import json




# Create your views here.
def home(request):

    product = Product.objects.all()
    
    return render(request, 'home.html',locals())
   
def index(request):
    return render(request, 'index.html')

def about(request):
    return render(request, 'about.html')

def main(request):
    return render(request, 'index.html')


def adminLogin(request):
    
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        try:
            if user.is_staff:
                login(request, user)
                messages.success(request, "Login Successfull")
                return redirect('admindashboard')
            else:
                messages.success(request, "Invalid Credentials")
        except:
           messages.success(request, "Invalid Credentials")
    
    return render(request, 'admin_login.html')


def adminHome(request):
    return render(request, 'admin_base.html')


def admin_dashboard(request):
    user = UserProfile.objects.filter()
    category = Category.objects.filter()
    product = Product.objects.filter()
    new_order = Booking.objects.filter(status=1)
    dispatch_order = Booking.objects.filter(status=2)
    way_order = Booking.objects.filter(status=3)
    deliver_order = Booking.objects.filter(status=4)
    cancel_order = Booking.objects.filter(status=5)
    return_order = Booking.objects.filter(status=6)
    order = Booking.objects.filter()
    read_feedback = Feedback.objects.filter(status=1)
    unread_feedback = Feedback.objects.filter(status=2)
    return render(request, 'admin_dashboard.html', locals())


def add_category(request):
    if request.method == "POST":
        name = request.POST['name']
        Category.objects.create(name=name)
        messages.success(request, "Category added")
        return redirect('view_category')
    return render(request, 'add_category.html', locals())

def view_category(request):
    category = Category.objects.all()
    return render(request, 'view_category.html', locals())


def edit_category(request, pid):
    category = Category.objects.get(id=pid)
    if request.method == "POST":
        name = request.POST['name']
        category.name = name
        category.save()
        msg = "Category Updated"
    return render(request, 'edit_category.html', locals())
 
def delete_category(request, pid):
    
    category = Category.objects.get(id=pid)
    category.delete()
    messages.success(request, "Category Deleted")
    return redirect('view_category')



def add_product(request):
    category = Category.objects.all()
    if request.method == "POST":
        name = request.POST['name']
        price = request.POST['price']
        cat = request.POST['category']
        discount = request.POST['discount']
        desc = request.POST['desc']
        image = request.FILES['image']
        catobj = Category.objects.get(id=cat)
        Product.objects.create(name=name, price=price, discount=discount, category=catobj, description=desc, image=image)
        messages.success(request, "Product added")
    return render(request, "add_product.html", locals())


def view_product(request):
    product = Product.objects.all()
    return render(request, 'view_product.html', locals())


def edit_product(request, pid):
    product = Product.objects.get(id=pid)
    category = Category.objects.all()
    if request.method == "POST":
        name = request.POST['name']
        price = request.POST['price']
        cat = request.POST['category']
        discount = request.POST['discount']
        desc = request.POST['desc']
        try:
            image = request.FILES['image']
            product.image = image
            product.save()
        except:
            pass
        catobj = Category.objects.get(id=cat)
        Product.objects.filter(id=pid).update(name=name, price=price, discount=discount, category=catobj, description=desc)
        messages.success(request, "Product Updated")
        return redirect('view_product')
    return render(request, 'edit_product.html', locals())


def delete_product(request, pid):
    product = Product.objects.get(id=pid)
    product.delete()
    messages.success(request, "Product Deleted")
    return redirect('view_product')


def registration(request):
    if request.method == "POST":
        fname = request.POST['fname']
        lname = request.POST['lname']
        email = request.POST['email']
        password = request.POST['password']
        address = request.POST['address']
        mobile = request.POST['mobile']
        image = request.FILES['image']
        user = User.objects.create_user(username=email, first_name=fname, last_name=lname, email=email, password=password)
        UserProfile.objects.create(user=user, mobile=mobile, address=address, image=image)
        messages.success(request, "Registeration Successful")
        return redirect('userlogin')
    return render(request, 'registration.html', locals())


def userlogin(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user:
            login(request, user)
            messages.success(request, "User login successfully")
            return redirect('home')
        else:
            messages.success(request,"Invalid Credentials")
    return render(request, 'userlogin.html', locals())


def profile(request):
    if not request.user.is_authenticated:
        return redirect('userlogin')
    user = User.objects.get(id=request.user.id)
    data = UserProfile.objects.get(user=user)
    if request.method == "POST":
        fname = request.POST['fname']
        lname = request.POST['lname']
        email = request.POST['email']
        address = request.POST['address']
        mobile = request.POST['mobile']
        try:
            image = request.FILES['image']
            data.image = image
            data.save()
        except:
            pass
        user = User.objects.filter(id=request.user.id).update(first_name=fname, last_name=lname)
        UserProfile.objects.filter(id=data.id).update(mobile=mobile, address=address)
        messages.success(request, "Profile updated")
        return redirect('profile')
    return render(request, 'profile.html', locals())

def logoutuser(request):
    logout(request)
    messages.success(request, "Logout Successfully")
    return redirect('home')

from django.contrib import messages

def change_password(request):
    if request.method == 'POST':
        o = request.POST.get('old')
        n = request.POST.get('new')
        c = request.POST.get('confirm')
        user = authenticate(username=request.user.username, password=o)
        if user is not None:
            if n == c:
                user.set_password(n)
                user.save()
                messages.success(request, "Password changed successfully")
                return redirect('home')
            else:
                messages.error(request, "New password and confirmation password do not match")
        else:
            messages.error(request, "Incorrect current password")
    return render(request, 'change_password.html')


def user_product(request,pid):
    if pid == 0:
        product = Product.objects.all()
    else:
        category = Category.objects.get(id=pid)
        product = Product.objects.filter(category=category)
    allcategory = Category.objects.all()
    return render(request, "user-product.html", locals())

def product_detail(request, pid):
    product = Product.objects.get(id=pid)
    latest_product = Product.objects.filter().exclude(id=pid).order_by('-id')[:10]
    return render(request, "product_detail.html", locals())


def addToCart(request, pid):
    myli = {"objects":[]}
    try:
        cart = Cart.objects.get(user=request.user)
        myli = json.loads((str(cart.product)).replace("'", '"'))
        try:
            myli['objects'][0][str(pid)] = myli['objects'][0].get(str(pid), 0) + 1
        except:
            myli['objects'].append({str(pid):1})
        cart.product = myli
        cart.save()
    except:
        myli['objects'].append({str(pid): 1})
        cart = Cart.objects.create(user=request.user, product=myli)
    return redirect('cart')


def incredecre(request, pid):
    cart = Cart.objects.get(user=request.user)
    if request.GET.get('action') == "incre":
        myli = json.loads((str(cart.product)).replace("'", '"'))
        myli['objects'][0][str(pid)] = myli['objects'][0].get(str(pid), 0) + 1
    if request.GET.get('action') == "decre":
        myli = json.loads((str(cart.product)).replace("'", '"'))
        if myli['objects'][0][str(pid)] == 1:
            del myli['objects'][0][str(pid)]
        else:
            myli['objects'][0][str(pid)] = myli['objects'][0].get(str(pid), 0) - 1
    cart.product = myli
    cart.save()
    return redirect('cart')


def cart(request):
    try:
        cart = Cart.objects.get(user=request.user)
        product = (cart.product).replace("'", '"')
        myli = json.loads(str(product))
        product = myli['objects'][0]
    except:
        product = []
    lengthpro = len(product)
    return render(request, 'cart.html', locals())


def deletecart(request, pid):
    cart = Cart.objects.get(user=request.user)
    product = (cart.product).replace("'", '"')
    myli = json.loads(str(product))
    del myli['objects'][0][str(pid)]
    cart.product = myli
    cart.save()
    messages.success(request, "Delete Successfully")
    return redirect('cart')


def booking(request):
    if not request.user.is_authenticated:

groceryapp/templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block body %}

    <!-- About Start -->
    
    <div class="container-xxl py-5">
        <div class="container">
            <div class="row g-5 align-items-center">
                <div class="col-lg-6 wow fadeIn" data-wow-delay="0.1s">
                    <div class="about-img position-relative overflow-hidden p-5 pe-0">
                        <img class="img-fluid w-100" src="{% static 'images/about.jpg' %}">
                    </div>
                </div>
                
                <div class="col-lg-6 wow fadeIn" data-wow-delay="0.5s">
                    <br>
                   <br>
                    <h1 class="display-5 mb-4">Best Organic Fruits And Vegetables</h1>
                    <p class="mb-4">Welcome to Pachakari.shop - Your One-Stop Online Shop for Fresh Fruits, Vegetables, and Dry Fruits!</p>
                    <p><i class="fa fa-check text-primary me-3"></i>At Pachakari.shop, we are passionate about bringing you the freshest and highest quality produce right to your doorstep. With a wide range of fruits, vegetables, and dry fruits, we aim to make your shopping experience convenient, affordable, and enjoyable.</p>
                    <p><i class="fa fa-check text-primary me-3"></i>We understand the importance of consuming fresh and healthy food, and that's why we source our products from trusted farmers and suppliers who share our commitment to quality. Our rigorous selection process ensures that only the finest and freshest items make it to your shopping cart. You can rest assured that every purchase you make from Pachakari.shop is of exceptional quality.</p>
                    <p><i class="fa fa-check text-primary me-3"></i>One of our primary goals is to make online grocery shopping a seamless and hassle-free experience for you. With our user-friendly website, you can easily navigate through our extensive collection of fruits, vegetables, and dry fruits. Find your favorites, discover new varieties, and explore seasonal produce all in one place.</p>
                    <a class="btn btn-primary rounded-pill py-3 px-5 mt-3" href="">Read More</a>
                </div>
            </div>
        </div>
    </div>
    <!-- About End -->


    <!-- Feature Start -->
    <div class="container-fluid bg-light bg-icon my-5 py-6">
        <div class="container">
            <div class="section-header text-center mx-auto mb-5 wow fadeInUp" data-wow-delay="0.1s" style="max-width: 500px;">
                <h1 class="display-5 mb-3">Our Features</h1>
                <p>Discover the Best Online Shopping Experience for Fresh Fruits, Vegetables, and Dry Fruits at Pachakari.shop!</p>
            </div>
            <div class="row g-4">
                <div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.1s">
                    <div class="bg-white text-center h-100 p-4 p-xl-5">
                        <img class="img-fluid mb-4" src="{%static 'images/icon-1.png' %}" alt="">
                        <h4 class="mb-3">Natural Process</h4>
                        <p class="mb-4">At Pachakari.shop, we follow a natural process to ensure that our fruits, vegetables, and dry fruits are sourced, handled, and delivered to you with utmost care, preserving their freshness and quality.</p>
                        <a class="btn btn-outline-primary border-2 py-2 px-4 rounded-pill" href="">Read More</a>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.3s">
                    <div class="bg-white text-center h-100 p-4 p-xl-5">
                        <img class="img-fluid mb-4" src="{%static 'images/icon-2.png' %}" alt="">
                        <h4 class="mb-3">Organic Products</h4>
                        <p class="mb-4">We take pride in offering a wide selection of organic fruits, vegetables, and dry fruits at Pachakari.shop, providing you with healthier options that are free from harmful pesticides and chemicals.</p>
                        <a class="btn btn-outline-primary border-2 py-2 px-4 rounded-pill" href="">Read More</a>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.5s">
                    <div class="bg-white text-center h-100 p-4 p-xl-5">
                        <img class="img-fluid mb-4" src="{%static 'images/icon-3.png' %}" alt="">
                        <h4 class="mb-3">Biologically Safe</h4>
                        <p class="mb-4">Your well-being is our priority, which is why we guarantee that all the products available at Pachakari.shop are biologically safe, meeting the highest standards of quality and hygiene.</p>
                        <a class="btn btn-outline-primary border-2 py-2 px-4 rounded-pill" href="">Read More</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Feature End -->
{% endblock body %}

groceryapp/templates/admin_login.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
<link rel="stylesheet" href=" {% static 'css/mystyle.css' %}  ">

<body id="login" style = "background-image : url({% static 'images/carousel-1.jpg' %})">

<class="mt-5">

<div class="container mt-5">
        <div class="row">
        <div class="col-lg-4 m-auto">
            <div class="card mt-5 bg-light">
            <div class="card-title text-center mt-3">
                <img src="{% static 'images/bear.png' %}" width="150" height="150">
                <h2 class="text-dark">Admin Login</h2>
            </div>
            <div class="card-body">
                <form method="post">
                {% csrf_token %}
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text">
                        <i class="fa fa-user fa-2x"></i>
                        </span>
                    </div>
                    <input type="text" name="username" class="form-control py-4" placeholder="UserName">
                </div>
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text">
                        <i class="fa fa-lock fa-2x"></i>
                        </span>
                    </div>
                    <input type="password" name="password" class="form-control py-4" placeholder="Password">
                </div>
                <input type="submit" value="Login" class="btn btn-success px-5">
                <a href="{% url 'home' %}" class="float-right mt-2 text-dark"><i class="fas fa-angle-double-left"></i> Go Back To HomePage </i></a>
                </form>
            </div>
            </div>
        </div>
        </div>

</div>

{% if msg %}
<script>
    alert('{{msg}}');
</script>
{% endif %}

{% endblock body %}

groceryapp/templates/manage_order.html
{% extends 'admin_base.html' %}
{% block main %}
{% load custom_tags %}
<div class="card shadow">
    <div class="card-body">
        <h5 class="p-2" style="border-bottom: 2px solid orange;">{{order_status}} Order</h5>
        <div class="container-fluid">
            <table class="table table-bordered table-sm" id="example">
                <thead>
                <tr>
                    <th>S.No.</th>
                    <th>OrderId</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Status</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                {% for i in order %}
                <tr>
                    <td>{{forloop.counter}}</td>
                    <td>{{i.id}}</td>
                    <td>{{i.user.first_name}} {{i.user.last_name}}</td>
                    <td>{{i.user.username}}</td>
                    <td>
                        <a href="/admin-order-track/{{i.id}}/" class="btn btn-primary" title="Track Status">{{i.get_status_display}}</a>
                    </td>
                    <td>
                        <!-- Button trigger modal -->
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal-{{forloop.counter}}">
                          <i class="fas fa-info"></i>
                        </button>

                        <!-- Modal -->
                        <div class="modal fade" id="exampleModal-{{forloop.counter}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                          <div class="modal-dialog" role="document">
                            <div class="modal-content">
                              <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel">Order Detail</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                  <span aria-hidden="true">&times;</span>
                                </button>
                              </div>
                              <div class="modal-body">
                                  <table width="100%">
                                      <tr>
                                        <th>Order Id</th>
                                        <td>{{i.id}}</td>
                                        <th>Status</th>
                                        <td>{{i.get_status_display}}</td>
                                      </tr>
                                      <tr style="background:black;color:white">
                                        <th colspan="4">Product Detail</th>
                                      </tr>
                                      {% for j in i.product|get_product %}
                                      <tr>
                                          <th>Product </th>
                                          <td colspan="2">{{j.name}}</td>
                                          <th>
                                            <img src="{{j.image.url}}" style="width:100%;height"80px>
                                          </th>
                                      </tr>
                                      <tr>
                                          <th>Quantity</th>
                                          <td>{% get_qty j.id i.id %}</td>
                                          <th>Price(per unit)</th>
                                          <td>Rs. {{j.price}}</td>
                                      </tr>
                                    {% endfor %}
                                      <tr>
                                        <th>Total Price</th>
                                        <td>Rs. {{i.total}}</td>
                                        <th>Booking Date</th>
                                        <td>{{i.created}}</td>
                                      </tr>
                                      <tr>
                                          <th colspan="4" style="background:black;color:white">
                                            <h4>User Detail</h4>
                                          </th>
                                      </tr>
                                      <tr>
                                          <th>Name</th>
                                          <td colspan="2">{{i.user.first_name}} {{i.user.first_name}}</td>
                                          <th colspan="1">
                                              <img src="{{i.user.userprofile_set.all.0.image.url}}" style="width:100%;height:80px">
                                          </th>
                                      </tr>
                                      <tr>
                                          <th>Email</th>
                                          <td>{{i.user.username}}</td>
                                          <th>Mobile</th>
                                          <td>{{i.user.userprofile_set.all.0.mobile}}</td>
                                      </tr>
                                      <tr>
                                          <th>Address</th>
                                          <td colspan="3">{{i.user.userprofile_set.all.0.address}}</td>
                                      </tr>
                                  </table>
                              </div>
                              <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                              </div>
                            </div>
                          </div>
                        </div>

                        <a href="/delete-order/{{i.id}}/?action={{request.GET.action}}" class="btn btn-danger"
                           onclick="return confirm('Are You Sure?')">
                            <i class="fas fa-trash-alt"></i>
                        </a>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

groceryapp/templates/my-order.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <title>My Order</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
{% include 'base.html' %}
<br>
<br>
<hr class="mt-5">
<div class="card shadow m-5" id="myorder">
    <div class="card-body">
        <div class="container-fluid">
            <h3 style="font-family:roman">My Order</h3>
            <table class="table table-bordered" style="width:100%">
                <thead>
                <tr>
                    <th>#</th>
                    <th>BookingID</th>
                    <th>TotalPrice</th>
                    <th>Status</th>
                    <th>CreationDate</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                {% for i in order %}
                <tr>
                    <td>{{forloop.counter}}</td>
                    <td>{{i.id}}</td>
                    <td>{{i.total}}</td>
                    <td><a href="/user-order-track/{{i.id}}/" class="btn btn-primary" title="Track Status">{{i.get_status_display}}</a></td>
                    <td>{{i.created}}</td>
                    <td>
                        {% if i.status < 4 %}
                            <a href="/change-order-status/{{i.id}}/?status=5" class="btn btn-success" title="Cancel Order"><i class="fa-solid fa-xmark"></i></a>
                        {% endif %}
                        {% if i.status == 4 %}
                            <a href="/change-order-status/{{i.id}}/?status=6" class="btn btn-danger" title="Return Order"><i class="fa-solid fa-refresh"></i></a>
                        {% endif %}
                        {% if i.status == 5 or i.status == 6 %}
                            -----
                        {% endif %}
                    </td>
                </tr>

                
                   
                </td>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
</body>
</html>